#!/usr/bin/env python3
"""Copy each graded problem's question into its answer key, directly above the solution.

A worked solution read without its question hides the scope of the problem: which
parts were asked, what data were given, what the student was told. A question pasted
into the key by hand goes stale the first time the problem set is edited, so the
questions in the keys are never maintained by hand. This script copies each one
verbatim from DayX/problem_set.html into DayX/problem_set_KEY.html, matched on the
exercise id (p1, p2, ...), inside a block fenced by comment markers. Re-running it
replaces every block, so an edited question reaches the key the next time it runs.

    python3 _tools/sync_key_questions.py           # update the keys
    python3 _tools/sync_key_questions.py --check   # exit 1 if any key is out of date

Run it after every edit to a problem set. --check writes nothing and is what catches
a forgotten run.

What is copied: everything in the exercise after its title, except the "Your answer
goes in the R Markdown hand-in" callout, which is a filing instruction rather than
part of the problem. id attributes are dropped so they cannot collide with the key's
own anchors. The block adds the problem's title only when the key does not already
show it (for example under a generic "Solution" heading), and adds the "Problem N"
tag only when the key has no exercise box of its own to carry one.

The keys are git-ignored and exist only on the instructor's machine. Nothing outside
the marked blocks and the one marked <style> block is ever modified.
"""
import argparse
import glob
import html
import os
import re
import sys

BLOCK_RE = re.compile(r'\n<!-- key-question:(p\d+) begin .*?<!-- key-question:\1 end -->\n', re.S)
CSS_RE = re.compile(r'\n<!-- key-question:css begin -->.*?<!-- key-question:css end -->\n', re.S)

BEGIN = ('<!-- key-question:{pid} begin | generated by _tools/sync_key_questions.py '
         'from problem_set.html. Edit the problem set and re-run; do not edit here. -->')
END = '<!-- key-question:{pid} end -->'

CSS = """<!-- key-question:css begin -->
<style>
  .key-q{border:1px solid #EBCFC2;border-left:5px solid var(--osu-orange);background:#FFF8F4;
    border-radius:0 9px 9px 0;padding:10px 16px 4px;margin:12px 0 18px;}
  .key-q-label{font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;
    color:var(--osu-orange-dark);margin:0 0 6px;}
  .key-q h3.key-q-title{margin:6px 0 8px;font-size:17px;color:var(--osu-black);}
  .key-q > :last-child{margin-bottom:8px;}
  /* lab.css styles these only inside .exercise; mirror them for keys with no exercise wrapper */
  .key-q .ex-tag{display:inline-block;background:var(--osu-orange);color:#fff;
    font-family:'Helvetica Neue',Arial,sans-serif;font-size:11px;font-weight:700;letter-spacing:1px;
    padding:4px 10px;border-radius:4px;text-transform:uppercase;}
  .key-q .difficulty{font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;color:var(--muted);margin-left:12px;}
  .key-q .difficulty.easy{color:var(--good);}
  .key-q .difficulty.medium{color:var(--warn);}
  .key-q .difficulty.hard{color:var(--bad);}
</style>
<!-- key-question:css end -->"""


def div_span(text, start):
    """(start, end) of the <div> opening at `start`, honouring nested divs."""
    depth = 0
    for m in re.finditer(r'<div\b|</div>', text[start:]):
        if m.group(0).startswith('<div'):
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                return start, start + m.end()
    return start, len(text)


def strip_tags(s):
    return ' '.join(html.unescape(re.sub(r'<[^>]*>', ' ', s)).split())


def drop_handin_callouts(body):
    """Remove 'Your answer goes in the R Markdown hand-in' callouts, nested-div safe."""
    spans = []
    for m in re.finditer(r'<div class="callout try"', body):
        a, b = div_span(body, m.start())
        if strip_tags(body[a:b]).startswith('Your answer'):
            spans.append((a, b))
    for a, b in reversed(spans):
        body = body[:a] + body[b:]
    return body


def read_questions(ps_html):
    """Map exercise id -> tag, difficulty, title and question body, in page order."""
    out = {}
    for m in re.finditer(r'<div class="exercise" id="(p\d+)"', ps_html):
        pid = m.group(1)
        a, b = div_span(ps_html, m.start())
        block = ps_html[a:b]
        inner = block[block.index('>') + 1:block.rindex('</div>')]
        tag = re.search(r'<span class="ex-tag">.*?</span>', inner, re.S)
        diff = re.search(r'<span class="difficulty[^"]*">.*?</span>', inner, re.S)
        h3 = re.search(r'<h3[^>]*>(.*?)</h3>', inner, re.S)
        body = inner[h3.end():] if h3 else inner
        body = drop_handin_callouts(body)
        body = re.sub(r'\s+id="[^"]*"', '', body)
        body = re.sub(r'\n{3,}', '\n\n', body).strip()
        out[pid] = {
            "tag": tag.group(0) if tag else '',
            "diff": diff.group(0) if diff else '',
            "title": h3.group(1).strip() if h3 else '',
            "body": body,
        }
    return out


def place(clean, pid, q):
    """Where the block goes in the key (with generated blocks removed), and whether the
    block must carry the problem tag and the title because the key does not show them.
    Returns (position, with_tag, with_title), or (None, None, None) if no solution."""
    m = re.search(r'<div class="exercise" id="%s"' % pid, clean)
    if m:
        a, b = div_span(clean, m.start())
        h3 = re.search(r'<h3[^>]*>(.*?)</h3>', clean[a:b], re.S)
        if h3 and strip_tags(h3.group(1)) == strip_tags(q["title"]):
            return a + h3.end(), False, False       # key shows tag and title: go under them
        if h3:
            return a + h3.start(), False, True      # generic heading such as "Solution"
        d = re.search(r'<span class="difficulty[^"]*">.*?</span>', clean[a:b], re.S)
        return (a + d.end() if d else a + clean[a:b].index('>') + 1), False, True
    m = re.search(r'<details class="answer" id="%s"' % pid, clean)
    if m:
        return m.start(), True, True                # bare answer toggle: nothing shown yet
    return None, None, None


def render(pid, q, with_tag, with_title):
    lines = [BEGIN.format(pid=pid), '<div class="key-q">',
             '<div class="key-q-label">Question, as students see it</div>']
    if with_tag:
        lines.append('<p style="margin:0;">' + q["tag"] + q["diff"] + '</p>')
    if with_title:
        lines.append('<h3 class="key-q-title">' + q["title"] + '</h3>')
    lines += [q["body"], '</div>', END.format(pid=pid)]
    return '\n'.join(lines)


def sync_day(day, check):
    ps_path = os.path.join(day, 'problem_set.html')
    key_path = os.path.join(day, 'problem_set_KEY.html')
    if not os.path.exists(key_path):
        return 'skip', ['no problem_set_KEY.html']

    questions = read_questions(open(ps_path, encoding='utf-8').read())
    original = open(key_path, encoding='utf-8').read()
    old_blocks = {m.group(1): m.group(0) for m in BLOCK_RE.finditer(original)}
    clean = CSS_RE.sub('', BLOCK_RE.sub('', original), count=1)

    problems, inserts = [], []
    for pid, q in questions.items():
        pos, with_tag, with_title = place(clean, pid, q)
        if pos is None:
            problems.append('%s is in the problem set but has no solution in the key' % pid)
            continue
        inserts.append((pos, pid, '\n' + render(pid, q, with_tag, with_title) + '\n'))
    key_ids = set(re.findall(r'<div class="exercise" id="(p\d+)"', clean)) | \
        set(re.findall(r'<details class="answer" id="(p\d+)"', clean))
    for pid in sorted(key_ids - set(questions), key=lambda s: int(s[1:])):
        problems.append('%s has a solution in the key but is no longer in the problem set' % pid)

    new = clean
    for pos, pid, block in sorted(inserts, reverse=True):
        new = new[:pos] + block + new[pos:]
    new = new.replace('</head>', '\n' + CSS + '\n</head>', 1)

    stale = [pid for _, pid, block in sorted(inserts) if old_blocks.get(pid) != block]
    orphans = sorted(set(old_blocks) - set(questions), key=lambda s: int(s[1:]))
    why = []
    if stale:
        why.append('out of date: ' + ', '.join(stale))
    if orphans:
        why.append('question block to remove, problem no longer exists: ' + ', '.join(orphans))
    if not why:
        why.append('question styling out of date')
    if new == original:
        return ('ok' if not problems else 'problems'), problems
    if check:
        return 'stale', problems + why
    open(key_path, 'w', encoding='utf-8').write(new)
    return ('updated' if not problems else 'problems'), problems + \
        ['refreshed %d question(s): %s' % (len(stale), ', '.join(stale))] if stale else problems


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='report stale keys and exit 1; write nothing')
    args = ap.parse_args()
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    failed = False
    for ps in sorted(glob.glob('Day*/problem_set.html')):
        day = os.path.dirname(ps)
        status, notes = sync_day(day, args.check)
        print('  {:34s} {}'.format(day, status))
        for n in notes:
            print('      ' + n)
        if status in ('stale', 'problems'):
            failed = True
    if args.check:
        print('  all keys match their problem sets' if not failed else
              '  run: python3 _tools/sync_key_questions.py')
    return 1 if failed else 0


if __name__ == '__main__':
    sys.exit(main())
