#!/usr/bin/env python3
"""
Regenerate the accessible/ content pages from the current standard site so the
two stay in sync after the v2/v3 merge and other edits.

Mirrors (copy + screen-reader transform) the standard content HTML into
accessible/, copies data + R + Rmd templates, and deletes retired files.

Does NOT touch the bespoke accessible files: index.html, accessibility.html,
lecture_*.html (generated by build_lecture_notes.py), and never copies answer
KEYs, .pptx, or the visual-only explore_*.html widgets.
"""
import os, re, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ACC = os.path.join(ROOT, "accessible")
DAYS = ["Day1_Probability", "Day2_GLM", "Day3_MixedModels_ModelSelection",
        "Day4_Likelihood_BayesI", "Day5_BayesII"]

ROOT_HTML = ["syllabus.html", "pre_course_exam.html", "post_course_exam.html",
             "rmarkdown_tutorial.html", "install_jags_nimble.html"]
DAY_HTML = ["lab.html", "problem_set.html", "plain_language_summary.html",
            "answer_key.html", "log_logit_intuition.html"]

CALLOUT_LABELS = {"plain":"Plain-language summary","bio":"Biological intuition",
                  "warn":"Watch out","key":"Key idea","try":"Try it yourself"}
ACCESSIBLE_MATHJAX = (
 '<script>\nMathJax = {\n'
 "  tex: { inlineMath: [['$','$'], ['\\\\(','\\\\)']] },\n"
 '  options: { menuOptions: { settings: { assistiveMml: true, explorer: true } } },\n'
 "  loader: { load: ['a11y/assistive-mml', 'a11y/explorer'] }\n};\n</script>\n"
 '<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script"></script>')
MATHJAX_RE = re.compile(r'<script>\s*MathJax\s*=\s*\{.*?</script>\s*<script[^>]*tex-chtml\.js[^>]*></script>', re.S)

PPTX_TO_NOTES = {
 "FW536_Day1_Morning_intro%20to%20probability.pptx":"lecture_day1_morning.html",
 "FW536_Day1_Afternoon%20Distributions%20I.pptx":"lecture_day1_afternoon.html",
 "FW536_Day2_Morning_ContinuousDistributions.pptx":"lecture_day2_morning.html",
 "FW536_Day2_Afternoon_GeneralizedLinear%20Models.pptx":"lecture_day2_afternoon.html",
 "FW536_Day3_Morning_mixed%20effects.pptx":"lecture_day3_morning.html",
 "FW536_Day3_Afternoon_hypothesis%20test%20and%20model%20selection.pptx":"lecture_day3_afternoon.html",
 "FW536_Day4_Morning_maximum%20likelihod.pptx":"lecture_day4_morning.html",
 "FW536_Day4_Afternoon_BayesI.pptx":"lecture_day4_afternoon.html",
 "FW536_Day5_BayesII.pptx":"lecture_day5.html",
}

def transform(text, depth):
    up = "../"*depth
    if 'data-a11y="done"' not in text:
        text = re.sub(r'<html lang="en">', '<html lang="en" data-a11y="done">', text, 1)
        if 'data-a11y="done"' not in text:
            text = text.replace("<html>", '<html lang="en" data-a11y="done">', 1)
    text = text.replace("css/lab.css","css/accessible.css").replace("js/lab.js","js/accessible.js")
    if "tex-chtml.js" in text:
        text = MATHJAX_RE.sub(lambda m: ACCESSIBLE_MATHJAX, text, 1)
    bar = (f'\n<a class="skip-link" href="#main-content">Skip to main content</a>\n'
           f'<div class="a11y-bar" role="region" aria-label="Accessibility">Accessible version &middot; '
           f'<a href="{up}accessibility.html">How to use this site with a screen reader</a> &middot; '
           f'<a href="{up}index.html">Course home</a></div>\n')
    if 'class="skip-link"' not in text:
        text = re.sub(r'<body>', '<body>'+bar, text, 1)
    text = re.sub(r'<nav>', '<nav aria-label="On this page and related documents">', text, 1)
    text = re.sub(r'<h1>(<a href="[^"]*index\.html"[^>]*>.*?</a>)</h1>', r'<p class="brand">\1</p>', text, 1)
    text = re.sub(r'<main class="content">', '<main class="content" id="main-content" tabindex="-1">', text, 1)
    if "callout-label" not in text:
        def add(m):
            cls=m.group("cls"); kind=None
            for k in CALLOUT_LABELS:
                if re.search(r'\b'+k+r'\b', cls): kind=k; break
            return m.group(0)+f'<p class="callout-label">{CALLOUT_LABELS.get(kind,"Note")}</p>'
        text = re.sub(r'<(?:div|section) class="(?P<cls>callout[^"]*)"[^>]*>', add, text)
    text = re.sub(r'<th(?![^>]*\bscope=)', '<th scope="col"', text)
    # lecture pptx links -> accessible notes
    for pptx,notes in PPTX_TO_NOTES.items():
        text = text.replace(f'href="{pptx}"', f'href="{notes}"')
    # drop links to the visual-only interactive widgets (drag-slider SVG/canvas
    # tools are not useful via a screen reader). Remove whole nav items, then
    # demote any remaining widget links to plain text so nothing breaks.
    text = re.sub(r'\s*<li><a href="[^"]*explore_[^"]*\.html">[^<]*</a></li>', '', text)
    text = re.sub(r'\s*<div class="activity-row"><span class="tag interactive">[^<]*</span>.*?</div>', '', text)
    text = re.sub(r'<a href="[^"]*explore_[^"]*\.html">([^<]*)</a>', r'\1', text)
    return text

def copy_html(src, dst, depth):
    t = transform(open(src, encoding="utf-8").read(), depth)
    open(dst, "w", encoding="utf-8").write(t)

def main():
    # retired files to remove from accessible
    for d in DAYS:
        for f in ("problem_set_v2.html","problem_set_v3.html","problem_set_v2_KEY.html",
                  "problem_set_v3_KEY.html","morning_lab_template_v2.Rmd","morning_lab_template_v3.Rmd",
                  "afternoon_lab_template_v2.Rmd","afternoon_lab_template_v3.Rmd"):
            p=os.path.join(ACC,d,f)
            if os.path.exists(p): os.remove(p)

    # root HTML
    for f in ROOT_HTML:
        src=os.path.join(ROOT,f)
        if os.path.exists(src): copy_html(src, os.path.join(ACC,f), 0)

    # day content
    for d in DAYS:
        os.makedirs(os.path.join(ACC,d), exist_ok=True)
        for f in DAY_HTML:
            src=os.path.join(ROOT,d,f)
            if os.path.exists(src): copy_html(src, os.path.join(ACC,d,f), 1)
        # templates + R + data (plain text / assets)
        for f in os.listdir(os.path.join(ROOT,d)):
            if re.match(r'(morning|afternoon)_lab_template\.Rmd$', f) or f.endswith(".R"):
                shutil.copy2(os.path.join(ROOT,d,f), os.path.join(ACC,d,f))
        # data folder
        srcdata=os.path.join(ROOT,d,"data")
        if os.path.isdir(srcdata):
            shutil.copytree(srcdata, os.path.join(ACC,d,"data"), dirs_exist_ok=True)
    print("accessible content pages regenerated from standard site")

if __name__ == "__main__":
    main()
